# .pre-commit-config.yaml
# https://github.com/kynan/nbstripout
repos:
- repo: https://github.com/kynan/nbstripout
  rev: 0.8.1
  hooks:
    - id: nbstripout

# - repo: local
#   hooks:
#     - id: collapse
#       name: Run my Python script
#       entry: python pre_commit_collapse.py
#       language: system